config/routes.rb
Rails.application.routes.draw do

  root 'games#new'

  resources :games, only: [:new, :create, :show] do
    get 'new_user', on: :member
    post 'add_user', on: :member
    resources :hands, only: [] do
      post 'distribute_cards', on: :collection
    end
    resources :game_turns, only: [:create] do
      put 'battle', on: :member
    end
  end
  
end

app/models/game.rb
require 'statistics'

class Game
  include Mongoid::Document
  include Mongoid::Timestamps

  NUMBER_OF_CARDS_BY_DECK = 3
  NUMBER_OF_PLAYERS = 2

  field :name, type: String
  field :players, type: Array, default: []

  has_many :game_turns
  has_many :hands

  validates_presence_of :name
  validate :check_number_of_player

  def distribute_cards(user)
    return unless CardToPlay.first
    deck = []
    NUMBER_OF_CARDS_BY_DECK.times do
      # TODO random card should be improved
      hand = self.hands.build(user_id: user.id, card_to_play_id: CardToPlay.all.sample.id)
      deck << hand if hand.save
    end
    deck
  end

  def winner
    ranking = Statistics.ranking_of_game(self.id)
    return if ranking.blank?
    return if ranking[1] && ranking[1]["count"] == ranking[0]["count"]
    return User.find(ranking[0]["_id"])
  end

  def check_number_of_player
    if self.players.count > NUMBER_OF_PLAYERS
      errors.add(:players, "maximum is #{NUMBER_OF_PLAYERS}")
    end
  end

  def players_to_user
    self.players.map{|user_id| User.find(user_id) }
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :find_game, only: [:new_user, :show, :add_user]
  before_filter :handle_game_path
  before_filter :set_players, only: [:show]

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to new_user_game_path(@game)
    else
      render :new
    end
  end

  def new_user
  end

  def show
    @hands_of_player_1 = hands_distributed(@player_1) if @player_1
    @hands_of_player_2 = hands_distributed(@player_2) if @player_2

    @game_turn_in_progress = @game.game_turns.where(status: GameTurn::IN_PROGRESS).first
    if @game_turn_in_progress
      @selected_card_1 = @game_turn_in_progress.hand_one.card_to_play
      @selected_card_2 = @game_turn_in_progress.hand_two.card_to_play
    end

    @game_turns_terminated = @game.game_turns.where(status: GameTurn::TERMINATED)
  end

  def add_user
    User.find_or_create({username: params[:username]}, @game)
    if @game.players.count == 2
      redirect_to game_path(@game)
    else
      redirect_to new_user_game_path(@game)
    end
  end

  private
  def game_params
    params.require(:game).permit(:name)
  end

  def find_game
    @game = Game.find(params[:id])
  end

  def set_players
    @game.players_to_user.each_with_index do |user, index|
      instance_variable_set("@player_#{index + 1}", user)
    end
  end

  def hands_distributed(user)
    @game.hands.where(user_id: user.id, status: Hand::DISTRIBUTED)
  end

  def handle_game_path
    if @game
      case @game.players.count
      when 0
        @active = "player_1"
        @path = new_user_game_path(@game)
      when 1
        @active = "player_2"
        @path = new_user_game_path(@game)
      when 2
        @active = "lets_go"
        @path = game_path(@game)
      end
    else
      @active = "game"
      @path = new_game_path
    end
  end

end

app/views/games/_card.html.erb
<div class="card card-big">
  <p><strong><%= card.name %></strong></p>
  <p><%= card.card_type.name %></p>
  <p>
    Level : <%= card.level %><br />
    Attack : <%= card.offensive_capacity %><br />
    Defense : <%= card.defense_capacity %>
  </p>
</div>

app/views/games/_deck.html.erb
<h4 class="text-center"><%= player.username %></h4>
<% if hands.any? %>
  <div class="row">
    <% hands.each do |hand| %>
      <div class="col-md-4">
        <div class="card card-thumb text-center">
          <%= f.radio_button field.to_sym, hand.id %>
          <p>Card</p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <%= link_to "distribute cards", distribute_cards_game_hands_path(game, user_id: player.id), method: :post, class: "btn btn-primary col-md-12" %>
<% end %>

app/views/games/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @game do |f| %>
      <%= f.text_field :name, class: "form-control input-lg", placeholder: "choose the game name..." %>
      <div class="submit-button">
        <%= f.submit class: "btn btn-primary pull-right" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_game_turns_list.html.erb
<% if game_turns.any? %>
  <table class="table table-striped table-of-game-turn">
    <thead>
      <tr>
        <th>#</th>
        <th><%= "#{user_1.username} remaining level" %></th>
        <th><%= "#{user_2.username} remaining level" %></th>
        <th>Winner of turn</th>
      </tr>
    </thead>
    <tbody>
      <% game_turns.each_with_index do |game_turn, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= game_turn.hand_one.remaining_level %></td>
          <td><%= game_turn.hand_two.remaining_level %></td>
          <td><%= game_turn.winner ? game_turn.winner.username : "-" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/games/new.html.erb
<%= render partial: "shared/breadcrumb" %>
<%= render partial: "form" %>

app/views/games/new_user.html.erb
<%= render partial: "shared/breadcrumb" %>
<h2 class="text-center"><%= @game.name %></h2>
<%= render partial: "users/form" %>

app/views/games/show.html.erb
<%= render partial: "shared/breadcrumb" %>
<h2 class="text-center"><%= @game.name %></h2>

<%= form_for [@game, @game.game_turns.new] do |f| %>

  <div class="row">

    <div class="col-md-3">
      <%= render partial: "deck", locals: { f: f, player: @player_1, hands: @hands_of_player_1, field: "hand_one_id", game: @game } %>
    </div>

    <div class="col-md-6">
      <%= render partial: "shared/alert_block" %>

      <div class="jumbotron">
        <% if @selected_card_1.present? && @selected_card_2.present? %>
          <div class="row">
            <div class="col-md-6">
              <%= render partial: "card", locals: { card: @selected_card_1 } %>
            </div>
            <div class="col-md-6">
              <%= render partial: "card", locals: { card: @selected_card_2 } %>
            </div>
          </div>
        <% end %>
      </div>

      <% if @selected_card_1.present? && @selected_card_2.present? %>
        <%= link_to "Battle", battle_game_game_turn_path(@game, @game_turn_in_progress), method: :put, class: "btn btn-warning col-md-12" %>
      <% elsif @hands_of_player_1.any? && @hands_of_player_2.any? %>
        <%= f.submit "Choose", class: "btn btn-primary col-md-12" %>
      <% elsif @game_turns_terminated.any? %>
        <h3 class="text-center text-danger">
          <% winner = @game.winner %>
          <%= winner.present? ? "**** THE WINNER IS #{winner.username} ****" : "**** ÉGALITÉ ****" %>
        </h3>
      <% end %>
    </div>

    <div class="col-md-3">
      <%= render partial: "deck", locals: { f: f, player: @player_2, hands: @hands_of_player_2, field: "hand_two_id", game: @game } %>
    </div>

  </div>

<% end %>

<%= render partial: "game_turns_list", locals: { game_turns: @game_turns_terminated, user_1: @player_1, user_2: @player_2 } %>